# These are supported funding model platforms

github: Mozes721
patreon: https://www.patreon.com/MozesCodes
buymeacoffe: https://www.buymeacoffee.com/MozesCodes
paypal: Mozes711@yahoo.com
eth: 0x7d630DB22e49201e25cEf4C1Ff89D58b658493fB
